"""edge_writer — append typed edges to wiki/graph/edges.jsonl (idempotent).

Per PLAN.md §5 — Tier A match-to-existing produces edge-only writes:
    voice/<memo> → existing wiki entry
Tier C propose-new produces:
    voice/<memo> → new entry  (derived_from)
    new entry → BM25-neighbor entries  (related_to)

`mentions` predicate is added to the 12-enum of edge types via this module —
existing enum already includes `mentions` per wiki/graph/edge-types.md, so no
constitutional add-and-extend needed.
"""

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


# Predicates allowed in voice→wiki and wiki→wiki edges generated by Stage 5
ALLOWED_PREDICATES = {
    "mentions",       # voice → wiki (Tier A/B match-to-existing)
    "derived_from",   # voice → wiki-new (Tier C propose-new origin)
    "related_to",     # wiki-new → wiki-existing (BM25 neighbors)
    "same_as",        # rare, alternate match-to-existing
}


def _normalize_edge(edge: Dict[str, Any]) -> str:
    """Canonicalize edge to JSONL line (sorted keys for idempotent dedup)."""
    # Mandatory keys
    out = {
        "from": edge["from"],
        "to": edge["to"],
        "type": edge["type"],
        "created": edge["created"],
        "confidence": edge.get("confidence", "medium"),
    }
    # Optional fields preserved if present
    for k in ("voice_score", "context", "bm25"):
        if k in edge:
            out[k] = edge[k]
    return json.dumps(out, ensure_ascii=False)


def _existing_edges_set(edges_path: Path) -> set:
    """Read existing edges and return a set of (from,to,type) tuples for dedup."""
    s = set()
    if not edges_path.exists():
        return s
    for line in edges_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            e = json.loads(line)
            s.add((e.get("from"), e.get("to"), e.get("type")))
        except Exception:
            continue
    return s


def append_edges(edges_path: Path, edges: Iterable[Dict[str, Any]]) -> Dict[str, int]:
    """Append edges; skip duplicates by (from,to,type). Validates predicate.

    Returns: {"appended": N, "skipped_dup": N, "rejected": N}
    """
    appended = 0
    skipped = 0
    rejected = 0
    edges_list = list(edges)
    if not edges_list:
        return {"appended": 0, "skipped_dup": 0, "rejected": 0}
    edges_path.parent.mkdir(parents=True, exist_ok=True)
    existing = _existing_edges_set(edges_path)

    out_lines: List[str] = []
    for e in edges_list:
        try:
            if e.get("type") not in ALLOWED_PREDICATES:
                rejected += 1
                continue
            if not e.get("from") or not e.get("to"):
                rejected += 1
                continue
            key = (e["from"], e["to"], e["type"])
            if key in existing:
                skipped += 1
                continue
            existing.add(key)
            out_lines.append(_normalize_edge(e))
            appended += 1
        except Exception:
            rejected += 1

    if out_lines:
        with edges_path.open("a", encoding="utf-8") as f:
            for ln in out_lines:
                f.write(ln + "\n")

    return {"appended": appended, "skipped_dup": skipped, "rejected": rejected}


def make_voice_to_wiki_edge(
    voice_memo_stem: str,
    wiki_path: str,
    *,
    predicate: str = "mentions",
    created: str,
    score: float,
    bm25: Optional[float] = None,
    confidence: Optional[str] = None,
) -> Dict[str, Any]:
    """Construct a voice→wiki edge. Confidence auto-derived from score if absent."""
    if confidence is None:
        confidence = "high" if score >= 0.85 else ("medium" if score >= 0.60 else "low")
    edge = {
        "from": f"voice/{voice_memo_stem}",
        "to": wiki_path,
        "type": predicate,
        "created": created,
        "confidence": confidence,
        "voice_score": round(score, 3),
    }
    if bm25 is not None:
        edge["bm25"] = round(bm25, 2)
    return edge


def make_neighbor_edge(
    new_wiki_path: str,
    neighbor_wiki_path: str,
    *,
    created: str,
    bm25: float,
) -> Dict[str, Any]:
    return {
        "from": new_wiki_path,
        "to": neighbor_wiki_path,
        "type": "related_to",
        "created": created,
        "confidence": "low",
        "bm25": round(bm25, 2),
    }


def make_voice_to_new_edge(
    voice_memo_stem: str,
    new_wiki_path: str,
    *,
    created: str,
) -> Dict[str, Any]:
    return {
        "from": f"voice/{voice_memo_stem}",
        "to": new_wiki_path,
        "type": "derived_from",
        "created": created,
        "confidence": "low",
    }


# ─── Smoke test ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import tempfile
    print("edge_writer smoke test")
    print("=" * 60)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as f:
        # Pre-existing edge to test dedup
        f.write(json.dumps({
            "from": "voice/audio_001", "to": "concepts/foo.md",
            "type": "mentions", "created": "2026-05-09", "confidence": "high",
        }) + "\n")
        path = Path(f.name)

    edges = [
        # New
        make_voice_to_wiki_edge("audio_587", "concepts/founder-isolation.md",
                                 created="2026-05-10", score=0.92, bm25=24.6),
        # Duplicate (matches pre-existing)
        make_voice_to_wiki_edge("audio_001", "concepts/foo.md",
                                 created="2026-05-10", score=0.95),
        # Rejected predicate
        {"from": "x.md", "to": "y.md", "type": "rolled_back",
         "created": "2026-05-10", "confidence": "high"},
        # Tier C
        make_voice_to_new_edge("audio_588", "ideas/new-masterskaya.md",
                                created="2026-05-10"),
        make_neighbor_edge("ideas/new-masterskaya.md",
                            "ideas/tools-feedback-community-flywheel.md",
                            created="2026-05-10", bm25=8.55),
    ]
    result = append_edges(path, edges)
    print(f"Result: {result}")
    print()
    print("Final edges file:")
    for line in path.read_text().splitlines():
        print(f"  {line}")
    path.unlink()
    print("=" * 60)
