"""Rebuild crm/index.md from crm/people/*.md + crm/orgs/*.md.

Idempotent: writes only if content differs from existing.
Performance target: <1s on 1000 records (we cache nothing in v1; trivial regex parse).
"""
from __future__ import annotations

import datetime as _dt
from collections import Counter
from pathlib import Path

from .frontmatter import parse_file, validate

CRM_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = CRM_ROOT / "index.md"


def _load_all() -> tuple[list[dict], list[str]]:
    records: list[dict] = []
    warnings: list[str] = []
    for kind, dirname in (("person", "people"), ("org", "orgs")):
        d = CRM_ROOT / dirname
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.md")):
            try:
                fm, _body = parse_file(path)
            except Exception as e:
                warnings.append(f"skip {path.name}: {e}")
                continue
            errs = validate(fm, file_hint=path.name)
            if errs:
                warnings.append(f"{path.name}: {len(errs)} schema errors (skipped from index)")
                continue
            records.append({"path": path, "fm": fm, "kind": kind})
    return records, warnings


def _slug_md(rec: dict) -> str:
    fm = rec["fm"]
    rel = "people" if rec["kind"] == "person" else "orgs"
    return f"[{fm['slug']}]({rel}/{fm['slug']}.md)"


def _short(s: str, n: int = 40) -> str:
    s = (s or "").replace("\n", " ").strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def render(records: list[dict]) -> str:
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    people = [r for r in records if r["kind"] == "person"]
    orgs = [r for r in records if r["kind"] == "org"]

    role_counts: Counter = Counter()
    role_slugs: dict[str, list[str]] = {}
    for r in records:
        for role in r["fm"].get("roles") or []:
            role_counts[role] += 1
            role_slugs.setdefault(role, []).append(_slug_md(r))

    lines: list[str] = []
    lines.append("<!-- Auto-generated by /crm-rebuild-index. Do not edit manually. -->")
    lines.append(f"<!-- Last: {now} -->")
    lines.append("")
    lines.append("# CRM Index — All Contacts")
    lines.append("")
    lines.append(f"**Total:** {len(records)} (people: {len(people)}, orgs: {len(orgs)})  ")
    lines.append(f"**Last rebuilt:** {now}")
    lines.append("")

    # By role
    lines.append("## By role")
    lines.append("")
    lines.append("| Role | Count | Slugs |")
    lines.append("|------|-------|-------|")
    for role in sorted(role_counts, key=lambda k: (-role_counts[k], k)):
        slugs = ", ".join(role_slugs.get(role, [])[:20])
        if len(role_slugs.get(role, [])) > 20:
            slugs += " …"
        lines.append(f"| {role} | {role_counts[role]} | {slugs} |")
    lines.append("")

    # All contacts
    lines.append("## All contacts")
    lines.append("")
    lines.append("| Slug | Name | Type | Roles | Status | ICP | Last touch | Country |")
    lines.append("|------|------|------|-------|--------|-----|------------|---------|")
    for r in sorted(records, key=lambda x: x["fm"].get("slug") or ""):
        fm = r["fm"]
        roles = ", ".join(fm.get("roles") or [])
        pipe = fm.get("pipeline") or {}
        icp_total = (fm.get("icp") or {}).get("total") or ""
        lines.append(
            f"| {_slug_md(r)} | {_short(fm.get('name'), 40)} | {r['kind']} | "
            f"{_short(roles, 32)} | {_short(pipe.get('status'), 18)} | "
            f"{icp_total} | {pipe.get('last_touch_date') or ''} | "
            f"{fm.get('location_country') or ''} |"
        )

    lines.append("")
    return "\n".join(lines) + "\n"


def rebuild(write: bool = True) -> tuple[str, list[str], bool]:
    """Returns (rendered, warnings, changed). If write=False, just returns rendered."""
    records, warnings = _load_all()
    new_content = render(records)
    changed = True
    if INDEX_PATH.exists():
        # idempotency: ignore the timestamp comment when comparing
        existing = INDEX_PATH.read_text(encoding="utf-8")
        if _strip_timestamp(existing) == _strip_timestamp(new_content):
            changed = False
    if write and changed:
        INDEX_PATH.write_text(new_content, encoding="utf-8")
    return new_content, warnings, changed


def _strip_timestamp(text: str) -> str:
    lines = []
    for ln in text.splitlines():
        if ln.startswith("<!-- Last:") or ln.startswith("**Last rebuilt:**"):
            continue
        lines.append(ln)
    return "\n".join(lines)


if __name__ == "__main__":  # pragma: no cover
    _, warnings, changed = rebuild(write=True)
    if warnings:
        print("warnings:")
        for w in warnings:
            print(f"  {w}")
    print(f"index.md {'rewritten' if changed else 'unchanged'}")
